#!/bin/bash

# # # # # # # # # # # # # # # # # # 
#
# A command to copy q and s forms
# to each other since people don't
# seem to adhere to standards
#
# This can copy q to s, or s to q
# based on the flag given.
#
# It appears that ANTs uses the q-form
# information and ignores s-form
#
# while...
#
# spm seems to use s-form
#
#
#
#
#                         Robert C. Welsh
#                         Copyright 2005-2018
#
# fixSQforms
#
# # # # # # # # # # # # # # # # # #

#
# Main newSeg function.
#

VERSION="1.0"
VERSIONDATE="2018-09-04"

# Find out where the current command lives and execute some common code.

theFullCommand="$0 $*"
execDIR=`pwd`

# Find out where the current command lives and execute some common code.

theCommand=`which $0`
thisDir=`dirname $theCommand`

thisCommand=`echo $theCommand | awk -F/ '{print $NF}'`

allowedOptions=" A d D f M n U v Q "

# This piece of code all of the spm12Batch scripts will use
. ${thisDir}/auxiliary/commonCode_AllScriptsStart

# This is the common in-line code for the copying s/q forms.
. ${thisDir}/auxiliary/commonCode_FSL_01

# This is common in-line code for all spm12Batch script to make sure arguments were passed
. ${thisDir}/auxiliary/commonCode_checkIfArgsPassed

#
# The actual function.
#

. ${thisDir}/auxiliary/parse_arguments

#

. ${thisDir}/auxiliary/superDebugStatus

#
# Ok - let's start displaying things back to the terminal
#

. ${thisDir}/auxiliary/shellScriptInfo

#
# Prepare to write the script.
#

# Makes sure they speficied some subjects.
. ${thisDir}/auxiliary/checkInputForSubjects

# Write out debug status
. ${thisDir}/auxiliary/debugStatus

# Ok, lets do the business.

# Print out the list of subjects that we operate upon.
. ${thisDir}/auxiliary/printSubjectsList

# Now start building the automatic scripts.

#
# the following environmental variables are from spm12Batch_Global
#
#    HOSTCOMPUTER     - name of the computer.
#    SCRIPTNAME       - name of the scripts to write.
#    UMBatchMatcher   - present working directory.
#    FULLSCRIPTNAME   - full path and name of scripts to write.
# 

. ${thisDir}/auxiliary/fixSQforms_part_01

# Common star to all shell scripts

. ${thisDir}/auxiliary/buildMatlabScripts_01

. ${thisDir}/auxiliary/shellScriptStart

. ${thisDir}/auxiliary/fslCommonScript

# Now build the list of directories for each subject.

declare -i is
declare -i ii

curDIR=`pwd`

# Prepare the directory where the work is to take place.


echo "    5) building shell script"
echo

# Now put in some varibles needed

. ${thisDir}/auxiliary/fixSQforms_part_02

# Now build the shell script command that will get launched into the background.

. ${thisDir}/auxiliary/startBashSubjectLoop

# Add the ANTS code to the shell script

. ${thisDir}/auxiliary/fixSQforms_part_03

. ${thisDir}/auxiliary/endBashSubjectLoop

# Now add the call for creation of the mask -- needs to be modifed for ANTS

#. ${thisDir}/auxiliary/shellScriptErode

# Finalize the shell script.

. ${thisDir}/auxiliary/shellScriptFinalize

# Now launch into the background if desired.

. ${thisDir}/auxiliary/shellScriptLaunch

#
# all done.
#
