#!/bin/bash

# # # # # # # # # # # # # # # # # # 
#
# A command to make it easier on the user to warp the 
# fmri time-series to the standard template.
#
# This command will build a script to run and will also 
# run the script in background.
#
#   e.g.   spm23Batch
#
#
#                         Robert C. Welsh
#                         Copyright 2005-2012
#
# spm12Batch
#
# # # # # # # # # # # # # # # # # #

#
# Main spm23Batch function.
#

VERSION="3.0"
VERSIONDATE="2017-02-13"

# Find out where the current command lives and execute some common code.

theFullCommand="$0 $*"
execDIR=`pwd`

# Find out where the current command lives and execute some common code.

theCommand=`which $0`
thisDir=`dirname $theCommand`

thisCommand=`echo $theCommand | awk -F/ '{print $NF}'`

# This piece of code all of the spm12Batch scripts will use
. ${thisDir}/auxiliary/commonCode_AllScriptsStart

# We only will print out the help and ignore everything!

#. ${thisDir}/auxiliary/help/${thisCommand}_Help

# Check for directories.

SPM12BATCHOK="spm12Batch and necessary elements appear all okay"
for ITEM in ${SPM12B1} ${SPM12B3}
do
    if [ ! -d ${ITEM} ]
    then       
	echo "Element missing : ${ITEM}"
	SPM12BATCHOK="spm12Batch and necessary elements appear to have a problem"
    fi
done

# Check for executables.

for ITEM in ${MATLAB} 3dDespike fslorient animaDistortionCorrection antsRegistration 
do
    THERE=`which ${ITEM}`
    if [ -z "${THERE}" ]
    then
	echo "Element missing : ${ITEM}"
	SPM12BATCHOK="spm12Batch and necessary elements appear to have a problem"
    fi
done
	    
echo
echo ${SPM12BATCHOK}
echo

exit 0

#
# all done.
#
